### ISSUE TITLE
feat: Add supervisors section, with `pacta.multi.loanbook.analysis` and `pacta.multi.loanbook.plot`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.sit.rep#16]
Would be good to include these repos in the SitRep.

@jacobvjk do you think it makes sense to add them already? (e.g. do they have R CMD check actions implemented and tests passing and maintainer defined and all that). Or should I wait?

**Comment by jacobvjk** [comment]
they both have R CMD checks that are passing, they both have maintainers, as far as they have tests, they are passing, but test coverage is not full at the moment. Up to you
