### ISSUE TITLE
R CMD action can have different names

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.sit.rep#19]
https://github.com/RMI-PACTA/pacta.sit.rep/blob/52c1c2f358c54a412da182504e475db42319ef8f/R/generate_package_table.R#L64

Because the filename of the action that runs R CMD checks in a repo is not fixed, the URL for its badge cannot be fixed, e.g. ...

https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/blob/main/.github/workflows/R.yml
https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/actions/workflows/R.yml/badge.svg

AB#10660

**Comment by jdhoffa** [comment]
Relates to
https://github.com/RMI-PACTA/pacta.multi.loanbook.analysis/issues/30
https://github.com/RMI-PACTA/pacta.multi.loanbook.plot/issues/24
