### ISSUE TITLE
feat: Add GH action to automatically update Transition Monitor Docker Build Status portion of `README.md`

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.sit.rep#4]
The [Transition Monitor Docker Build Status](https://github.com/RMI-PACTA/pacta.sit.rep?tab=readme-ov-file#transition-monitor-docker-build-status) is currently just a static placeholder for info that should be automatically updated. 

I would like to have a GitHub action that:
* Takes the latest `nightly` build of `workflow.transition.monitor`: https://github.com/RMI-PACTA/workflow.transition.monitor/pkgs/container/workflow.transition.monitor/194298613?tag=nightly
*  Builds private images with the appropriate PACTA data
* Updates the Build Status table in the `README.md` of this repo with appropriate build info and links to the dev reports

To be based heavily on https://github.com/RMI-PACTA/workflow.transition.monitor/blob/main/.github/workflows/build-and-push-Docker-image.yml

cc @AlexAxthelm 

AB#10661

**Comment by AlexAxthelm** [comment]
@jdhoffa Not self contained, but you may want to look at the invocation of the `add-comment` action in `workflow.transtion.monitor`. Right now, it's set to only run if it's on a PR event, but it wouldn't be difficult to have it trigger a push here on `scheduled` events (which are the ones that are building `nightly`).

https://github.com/RMI-PACTA/workflow.transition.monitor/actions/runs/8383423748

**Comment by jdhoffa** [comment]
@AlexAxthelm so just to understand, the approach you suggest here would be something like: 
* In `workflow.transition.monitor`: duplicate the `add-comment` action (but maybe name it something like `update-sit-rep`) to run `nightly` (using all the `latest` on `main` packages)
* Give that new action write access to this repo (`pacta.sit.rep`), and have it push a PR that updates the `README` directly? 

something like that?

**Comment by jdhoffa** [comment]
Superseded by #27
