### ISSUE TITLE
add workflow.benchmark.preparation

### ISSUE THREAD

**Issue by cjyetman** [RMI-PACTA/pacta.sit.rep#51]
add [workflow.benchmark.preparation](https://github.com/RMI-PACTA/workflow.benchmark.preparation) once it's fully setup

**Comment by cjyetman** [comment]
not really sure what it would mean to be "fully setup" anymore... @jdhoffa?

**Comment by jdhoffa** [comment]
I think it's probably as ready as it will ever be!

**Comment by jdhoffa** [comment]
@cjyetman would you ever imagine the `workflow.*` sit rep info living in the `pactaverse` pkgdown website? or no? 

I was considering archiving this repo in favour of that new page, but now it seems like we'd miss out on some crucial info if we did so.

**Comment by cjyetman** [comment]
> @cjyetman would you ever imagine the `workflow.*` sit rep info living in the `pactaverse` pkgdown website? or no? 
> 
> 
> 
> I was considering archiving this repo in favour of that new page, but now it seems like we'd miss out on some crucial info if we did so. 

Maybe, but probably not. I think keeping it to R pkgs makes more sense.

**Comment by jdhoffa** [comment]
Yeah I had the same feeling... In that case, it seems like we still need this repo 😃
