### ISSUE TITLE
feat: consider if we want to do any situation report on our `workflow.*` style repositories

### ISSUE THREAD

**Issue by jdhoffa** [RMI-PACTA/pacta.sit.rep#7]
Noting that the "Transition Monitor Docker Build Status" section that @AlexAxthelm has created already assess very well if the entire `workflow.transition.monitor` build process runs (and displays the output reports of the build process). 

We may want to consider running checks on the stability of `workflow.scenario.preparation` or `workflow.data.prepartion` etc.?
At this stage I'm not even really sure what relevant information we would be able to show there.

cc: @cjyetman @AlexAxthelm

**Comment by cjyetman** [comment]
Love the idea, but don't have any suggestions on how to achieve it at the moment. Feel free to ping me in the future to put some thought into it again.
